### ISSUE TITLE
管理员进行帖子设置管理时会引发500错误

### ISSUE THREAD

**Issue by expoli** [csfwff/rhythm#1]
### 描述问题 Describe the problem

管理员进行帖子设置管理时会引发500错误

### 期待的结果 Expected result

正常调出帖子管理界面

### 截屏或录像 Screenshot or video

https://user-images.githubusercontent.com/31023767/132265779-f3e8182f-6fbc-402d-834d-1076c31e6123.mp4

### 版本环境 Version environment

* 版本 Version：3.6.2
* 操作系统 Operating system：Android
* 浏览器（如果使用）Browser (if used)：Firefox

### 其他信息 Other information

（昨天还正常🧐

**Comment by expoli** [comment]
测试了一下、只是在移动版网页会出现这个情况

**Comment by adlered** [comment]
收到了，墨夏已经在改，感谢

**Comment by csfwff** [comment]
😬改好了的 closed
