### ISSUE TITLE
第一次提交帖子提示系统错误

### ISSUE THREAD

**Issue by SkySunStar** [csfwff/rhythm#107]
### 描述问题 Describe the problem
刚注册后，写个新人报道帖子，提交后就提示系统错误

### 期待的结果 Expected result
提交成功的提示

### 截屏或录像 Screenshot or video

![image](https://user-images.githubusercontent.com/45973370/215307609-9b93eaa0-21fa-4873-8c2c-bd33bc0b8bc4.png)

### 版本环境 Version environment

* 版本 Version：https://fishpi.cn
* 操作系统 Operating system：Windows 11
* 浏览器（如果使用）Browser (if used)：Opera

**Comment by imufwt** [comment]
尝试刷新重试下.

**Comment by gakkiyomi** [comment]
先关闭
