### ISSUE TITLE
私聊页面点图片新开标签打开

### ISSUE THREAD

**Issue by KwdeTfpv** [csfwff/rhythm#144]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
私聊页面点击图片的话，会在当前页面打开，按退回的话，并不是退回到点击图片前的页面

### 描述最优的解决方案 Describe the optimal solution
新开标签打开图片或者当前页面打开图片点回退能退到点开图片时的页面

**Comment by adlered** [comment]
你好，私聊界面的图片在打开后可以再次点击关闭
