### ISSUE TITLE
GitHub Action Docker 镜像自动构建（在写了-等会测试完了pr过来）

### ISSUE THREAD

**Issue by expoli** [csfwff/rhythm#3]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

- 快速构建
- 快速部署
- 节约自主构建时间

### 描述最优的解决方案 Describe the optimal solution

Github Action 自动构建

**Comment by expoli** [comment]
> 笑死🤣卡住了

**Comment by adlered** [comment]
这也能搞？666

**Comment by expoli** [comment]
> 这也能搞？666

已经卡住了、笑死、可能是镜像问题

**Comment by adlered** [comment]
坐等你的Docker

**Comment by expoli** [comment]
#64

**Comment by expoli** [comment]
咕咕咕 到现在了（笑死）

**Comment by adlered** [comment]
咕咕咕
