### ISSUE TITLE
聊天室历史消息重复

### ISSUE THREAD

**Issue by imlinhanchao** [csfwff/rhythm#39]
### 描述问题 Describe the problem

打开聊天室，等待新消息进入，再下滑加载历史消息。新载入消息会出现与之前相同的消息。

### 建议做法

`/chat-room/more` 接口使用最后一笔消息时间戳或 `oId` 作为参数，而不是 `page`。返回该消息后 30 笔消息列表。

**Comment by adlered** [comment]
3f2b2f85

**Comment by imlinhanchao** [comment]
阿大也太偷懶了吧
