### ISSUE TITLE
聊天输入框 表情栏建议放大点

### ISSUE THREAD

**Issue by FreeEasy-Z** [csfwff/rhythm#43]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

对于喜欢用表情的人来说，每次翻表情着实比较痛苦，因为框太小，可见的选择范围比较少

### 描述最优的解决方案 Describe the optimal solution

当然是放大点 长宽都放大点，例如微信一行15个表情，至少有7行完整表情

### 描述候选解决方案 Describe the candidate solution

放大 放大 可见选择范围多一些

### 其他信息 Other information

木有了

**Comment by FreeEasy-Z** [comment]
web端的

**Comment by adlered** [comment]
是编辑器里的表情按钮，还是编辑器下面的表情包按钮？

**Comment by FreeEasy-Z** [comment]
![图片](https://user-images.githubusercontent.com/32925072/153831500-3996d2dc-c557-4637-861b-fe0881f93cd0.png)
常用表情栏

**Comment by adlered** [comment]
表情可以用快捷消息的哈，比如 :huaji: :doge: 之类的
