### ISSUE TITLE
文章链接打开500

### ISSUE THREAD

**Issue by Suvern** [csfwff/rhythm#56]
### 描述问题 Describe the problem

https://fishpi.cn/article/1638878461767

### 期待的结果 Expected result

正常打开

### 截屏或录像 Screenshot or video

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/38653369/164159313-94ccf0fa-e4b2-47d9-9c90-910dc1127f6b.png">

**Comment by adlered** [comment]
本帖应当事人要求已被封禁，无法访问，敬请谅解
